---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(lubridate)
library(tidyverse)
library(tsibble)
library(tsibbledata)
library(feasts)
library(nycflights13)

date1 <- ymd_hms("2017-04-22 22:01:18")
date2 <- ymd_hms("2001-11-07 10:09:56")


```

# Dates and Times
Question 1

```{r}
year(date1)
month(date1)
mday(date1)
yday(date1)
wday(date1)
```

Question 2

```{r}
next_fortnight <- date1 + days(14)

previous_decade <- date2 - years(10)
```

Question 3

```{r}
this_year <- today()

interval_years <- lubridate::interval(this_year, previous_decade)
```


Question 4

```{r}
nyc_date1 <- with_tz(date1, "America/New_York")
nyc_date2 <- with_tz(date2, "America/New_York")
```

Question 5

```{r}
flights %>% 
  mutate(departure_date = make_datetime(year, month, day, hour, minute))
```

# Time series familiarity
Question 6



```{r}
head(weather)

weather <- weather %>% 
  select(origin, temp, humid, precip, time_hour)

#key is origin?
#Index is  time_hour
#Hourly data daily
```

Question 7


```{r}
weather <- weather %>% 
  as_tsibble(key = origin, index = time_hour)
```


Question 8

```{r}
weather <- weather %>% 
  mutate(year = year(time_hour),
         month = month(time_hour))

weather %>%
  ggplot(aes(time_hour, temp)) +
  geom_line() 

```

Question 9

Question 10


Question 11

Question 12
















