---
title: "Tidyverse Consolidation"
output: html_notebook
---
```{r}
library(tidyverse)
```

1
```{r}
code_clan_tweets <- read_csv("code_clan_tweets.csv")
dim(code_clan_tweets)
names(code_clan_tweets)
```
2
```{r}
boxplot(code_clan_tweets$favorite_count)
```

3
```{r}
code_clan_tweets %>% 
  filter(is_quote == FALSE) %>% 
  select(favorite_count) %>% 
  summarise(n())
```

4
```{r}
code_clan_tweets %>% 
  filter(is_quote == FALSE) %>%
  group_by(source) %>% 
  summarise(mean_retweet_count = mean(retweet_count))
```

5
```{r}
code_clan_tweets %>%
  mutate(media_type = replace(media_type, is.na(media_type), "text")) %>%
  group_by(media_type) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))
  
```

6
```{r}
code_clan_tweets %>% 
  select(text) %>%
```
7

```{r}
code_clan_tweets %>% 
  summarise(mean(str_length(text[1:234])))
```

```{r}
code_clan_info <- read_csv("code_clan_info.csv")
view(code_clan_info)
```
8
```{r}
joined_data <- code_clan_tweets %>% 
  left_join(code_clan_info, by = "tweet_id")
```


9
```{r}
codeclan_hashtags <- joined_data %>% 
  select(tweet_id, hashtags) %>% 
  mutate(lowcase_hashtags = str_to_lower(hashtags)) %>% 
  select(-hashtags) %>% 
  drop.na(lowcase_hashtag)
  
```

