---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(MASS)
```

1

```{r}
items <- read_csv("data/20190928-items.csv")
clean_names(items)
```

2
```{r}
items %>% 
  group_by(brand) %>% 
  tally() %>% 
  top_n(1)
```


3
```{r}
stats_items <- items %>% 
  filter(brand == "Samsung") %>% 
  summarise(
    mean = mean(rating),
    sd = sd(rating)
  )
stats_items


items %>% 
  filter(brand == "Samsung") %>% 
  ggplot(aes(x = rating)) +
  geom_histogram(aes(y = ..density..), col = "white") +
  stat_function(
    fun = dnorm, 
    args = list(
      mean = stats_items$mean, 
      sd = stats_items$sd
    ),
    col = "green"
  )

# Yeah the normal distribution does provide a good model as the line fits the same general pattern as the data
```


4

```{r}

100 * (pnorm(q = stats_items$mean) - pnorm(q = 1))
100 * (pnorm(q = stats_items$mean) - pnorm(q = 2))
100 * (pnorm(q = stats_items$mean) - pnorm(q = 3))


items %>%
  filter(rating >= stats_items$mean - stats_items$sd) %>%
  filter(rating <= stats_items$mean + stats_items$sd) %>%
  summarise(prop_within_1sd = n() / nrow(items))

```
Extension
```{r}
?qqnorm
```

