---
title: "R Notebook"
output: html_notebook
---
1 MVP
```{r}

library(keyring)
library(RPostgreSQL)
keyring_unlock(keyring = "local")
username <- key_get(service = "postgresql_username", keyring = "local")
password <- key_get(service = "postgresql_password", keyring = "local")
keyring_lock(keyring = "local")

db_connect <- (dbConnect(drv = PostgreSQL(max.con = 1),
                         user = username,
                         password = password,
                         dbname = 'acme_employees',
                         host = "localhost")
                        )

rm(password, username)
```


```{r}
employees_df <- dbGetQuery(db_connect,
           "SELECT * 
           FROM employees")

feedbacks_df <- dbGetQuery(db_connect,
           "SELECT * 
           FROM feedbacks")

teams_df <- dbGetQuery(db_connect,
           "SELECT * 
           FROM teams")


```


```{r}
dbGetQuery(db_connect, 
            "SELECT first_name, last_name, 
            CONCAT(first_name, ' ', last_name) 
            AS full_name
            FROM employees")
```

```{r}
dbGetQuery(db_connect, 
            "SELECT t.name AS team_name, COUNT(t.id) AS num_employees
            FROM employees AS e
            RIGHT JOIN teams AS t
            ON e.team_id = t.id
            GROUP BY t.name
            ORDER BY num_employees DESC")
```

```{r}
dbGetQuery(db_connect, 
            "SELECT *
            FROM employees
            WHERE email NOT LIKE '%@%' OR email IS NULL")

```


2 Extensions
2.1 Harder SQL queries

```{r}
dbGetQuery(db_connect, 
            "SELECT *
            FROM employees AS e
            INNER JOIN feedbacks AS f
            ON e.id = f.employee_id
            ORDER BY f.date DESC
            LIMIT 1")
```


```{r}
dbGetQuery(db_connect, 
            "SELECT t.name, COUNT(t.id) AS num_initials
            FROM employees AS e
            INNER JOIN teams AS t
            ON e.team_id = t.id
            WHERE e.first_name LIKE '_' 
            GROUP BY t.name
            ORDER BY num_initials DESC
            LIMIT 1")
```

2.2
```{r}
positive_words <- c("great", "good", "happy", "content", "fulfilled", "fulfilled", "positive", "positives", "cheerful", "nice", "ambition", "ambitions", "ambitious", "friendly", "progress", "joy", "fast", "achieve", "achieving", "achievements", "best", "better",  "unlimited", "pros", "competitive", "opportunity", "advancement", "friendly", "smart", "interesting", "challenging", "grow", "caring", "balance", "helpful")

negative_words <- c("worse", "worsening", "worst", "slow", "sluggish", "impatient", "unfulfilled", "unfulfilling", "negative", "bad", "limited", "limit", "limitations", "cons", "frustrated", "frustrating", "frustration", "dull", "boring", "politics", "political", "ignore", "ignored", "ignoring", "sad", "depressed", "depressing", "nasty", "stress", "stresses", "stressed", "horrid", "horrible", "terrible", "deadline", "deadlines", "uncaring", "remote")
```



```{r}
library(stringr)
feedback <- dbGetQuery(db_connect,"
                       SELECT message
                       FROM feedbacks")
feedback <- toString(feedback)
messages_nopunc <- gsub("[[:punct:]]", "", feedback)
messages <- tolower(messages_nopunc)
 
score_messages <- function(x){
  
}
```



```{r}

```



```{r}
dbDisconnect(db_connect)
```