---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(GGally)
library(fastDummies)
```

```{r}
diamonds <- read_csv("diamonds.csv")
```

```{r}
summary(diamonds)
ggpairs(diamonds, columns = c("carat", "x", "y", "z"))

```

```{r}
diamonds_dropped <- diamonds %>% 
  select(
    -x,
    -y, 
    -z
  )
```

```{r}
ggpairs(diamonds_dropped)
```

```{r}
diamonds_dropped %>% 
  ggplot(aes(carat, price)) +
  geom_point()
```

```{r}
#cut - 4 dummies
unique(diamonds_dropped$cut)

#clarity - 7 dummies
unique(diamonds_dropped$clarity)

#color - 6 dummies
unique(diamonds_dropped$color)
```

```{r}
#creating dummy variables for cut, clarity, color and dropping th original columns
diamond_dummies <- diamonds_dropped %>% 
  dummy_cols(select_columns = c("cut", "clarity", "color"), remove_first_dummy = T) %>% 
  select(-cut, -clarity, -color)
```

```{r}
# SImple linear regression price & carat
model <- lm(price ~ carat, data = diamonds_dropped)

plot(model)
summary(model)
```

```{r}
model2 <- lm(price) ~ log(carat), data = diamonds_dropped)

summary(model2)
```
very high r2 value and strong p values 

```{r}

```









