---
title: "Data Loading"
output: html_notebook
---
Data.csv
Read in the data (where any blank characters will come through as NA) and examine the contents of the dataframe. Do you see that only part of the dataframe contains useful data?
```{r}

```

Find the index of the row in the dataframe at which the data starts, and save this to a variable min_which_not_na. Remember, try to do this programatically: write code to detect where the data starts (i.e. don’t just manually inspect the dataframe and then set min_which_not_na <- 4).
Hints


Find the index of the row in the sheet at which the data ends, and save this to a variable max_which_not_na. As above, do this programatically!
Hints


Now use the row indices min_which_not_na and max_which_not_na calculated above to subset the dataframe to only the useful rows.

So we have the rows containing the useful data. Now we need to remove the columns in which all entries are NA.
Hints


Take the first row of the useful data and use it to set column names. Delete this row.