---
title: "Extra Week 1 Qs"
output: html_notebook
---
1 Creating and converting vectors
1.1 Creating vectors

```{r}
my_double <- c(5.64, 67, 89.4)
my_integer <- c(4L, 87L, 24L)
my_character <- c("Liz", "Craig", "Apple", "Plant")
my_factor <- factor("Hippo", "Giraffe", "Tangerine")
my_logical <- c(TRUE, FALSE, TRUE, TRUE, FALSE)

```

1.2 Checking classes

```{r}
class(my_double)
class(my_integer)
class(my_character)
class(my_factor)
class(my_logical)
```

1.3 More checking classes

```{r}
is.double(my_double)
is.integer(my_integer)
is.character(my_character)
is.factor(my_factor)
is.logical(my_logical)
```
1.4 Converting
```{r}
class(as.integer(my_double))
class(as.character(my_double))
class(as.factor(my_double))
class(as.logical(my_double))
```

1.5 Converting numbers

```{r}
numbers_character <- c("4", "5", "5")
numbers_factor <- factor(numbers_character)
as.integer(numbers_character)
as.integer(numbers_factor)
#It shows the levels not the values
```
```{r}

```
2 Using functions and operators
2.1 Fibonacci numbers

```{r}
fib <- c(1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233)
fib <- append(fib, c(377, 610, 987))
fib
```

```{r}
sort(fib, decreasing = TRUE)

```

```{r}
sum(fib %% 2 == 0)
```

```{r}
part <- (sum(fib %% 2 == 0))
whole <- (length(fib))

part/whole*100
```

```{r}
fib[10]
```

```{r}
golden_ratio <- (1 + sqrt(5))/2
nth_golden_ratio <- function(n){
  (golden_ratio^(n) - ((1 - golden_ratio)^(n)))/sqrt(5)
}

nth_golden_ratio((1:16))
```


```{r}
1/1
1/2
2/3
3/5

```


3 Functions and Control flow
3.1

```{r}
my_func <- function(n){
  # ifelse(n < 10, x <- n, ifelse(n >= 10, x <- n / 10, ifelse(class(x) != "numerical", x<- "Invalid input"))
  # append("The answer is:", x)}
  if (n < 10){ 
    x <- n
  return (append("The answer is:", x))
  }
  if (n >= 10){
    x <- (n / 10)
    return(append("The answer is:", x))
  }
  else {
    "Invalid input"
    }


my_func("oh")
```

3.2

```{r}
c <- c(1, 2, 3, 4, 5)
d <- c(1, 2, 3, 4, 5)
e <- c(6, 7, 8, 9, 10)
check_same <- function(a, b){
  if (a == b){
    "Same"
  } else{
    "Different"
  }
}
check_same(c, e)
```
 
```{r}

```







