---
title: "R programming - Weekend Homework"
output: html_notebook
---

```{r}
library(dplyr)
```

2.2 if statements and functions

2.2.1

```{r}
multiply_15_add_4 <- function(x){
  x*15+4
}

multiply_15_add_4(1)
multiply_15_add_4(2)
multiply_15_add_4(3)
multiply_15_add_4(24)
```
2.2.2

```{r}


test_bird <- function(x){
  birds <- c("goose", "duck", "pigeon")
  
  if (x %in% birds){
    return("bird")
  } else {
    "not bird"
  }
}

test_bird("goose")
test_bird("apple")
test_bird(5)


```
2.2.3

```{r}
multiply_10 <- function(x){
  if (class(x) == "numeric"){
    return(x*10)
  }
  else
    return("Invalid input")
}

multiply_10("hello")
```
2.3 ifelse(), recode() and case_when()
2.3.1

```{r}
sizes <- c(13, 15, 10, 8, 22)
```

```{r}
sizes_new <- ifelse(sizes > 10, "Big", "Small")

sizes_new
```
recode()
```{r}

sizes <- c(13, 15, 10, 8, 22)

new_sizes <- as.factor(sizes <= 10)

recode(new_sizes, "FALSE" = "Small", "TRUE" = "Big")
```
case_when()
```{r}
sizes_new_3 <- case_when(
  sizes > 10 ~ "Big",
  sizes <= 10 ~ "Small"
)

sizes_new_3
```

2.3.2

apple → alpaca
banana → bonobo
cherry → chipmunk
```{r}
#apple → alpaca
# banana → bonobo
# cherry → chipmunk
fruit <- c("apple", "apple", "banana", "cherry", "cherry")
```
ifelse()
```{r}
ifelse(
  fruit == "apple", "alpaca",
  ifelse(fruit == "banana", "bonobo",
         ifelse(fruit == "cherry", "chipmunk",
                NA)
         )
  )
```
recode()

```{r}
fruit <- c("apple", "apple", "banana", "cherry", "cherry")

recode(fruit,
       "apple" = "alpaca", 
       "banana" = "bonobo", 
       "cherry" = "chipmunk"
)

fruit
```
case_when(
```{r}
fruit <- c("apple", "apple", "banana", "cherry", "cherry")

conversions <- case_when(
  fruit == "apple" ~ "alpaca",
  fruit == "banana" ~ "bonobo",
  fruit == "cherry" ~ "chipmunk"
)
conversions
```
2.3.3

```{r}
wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)
```
ifelse()
```{r}
ifelse(wife_age < husband_age, "Husband older", ifelse(wife_age > husband_age, "Wife Older", "Same age"))
```
recode()
```{r}
wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)

# new_sizes <- as.factor(sizes <= 10)

# recode(new_sizes, "FALSE" = "Small", "TRUE" = "Big")
```
case_when()
```{r}
case_when(
  wife_age  < husband_age  ~ "Husband older",
  wife_age  > husband_age  ~ "Wife older",
  wife_age == husband_age  ~ "Same age"
)
```
2.4 Loops
```{r}
my_list <- list(
  4,
  "apple",
  10.5,
  c("is", "an", "apple"),
  "apple",
  c("i", "like", "apples"),
  8
)
```
2.4.1

```{r}
for(elem in my_list){
  if(is.character(elem)){
    print(elem)
  }
} 

```

2.4.2

```{r}
while(my_list == "character")
```

2.4.3

```{r}

```


3 Extension - Puzzles
3.1


```{r}
multiplication_table <- ?outer(1:12, 1:12, "*")
rownames(multiplication_table) <- paste(1:12)

multiplication_table
```
3.2

```{r}

```















