---
title: "Homework"
output: html_notebook
---
1 MVP
Question 1
```{r}
library(tidyverse)
```

1
```{r}
drinks_content <- read_csv("data/starbucks_drinkMenu_expanded.csv")
head(drinks_content, 5)
tail(drinks_content, 5)
dim(drinks_content)
names(drinks_content)
```

Question 2

```{r}
summary_calories <- summarise(drinks_content, mean = mean(Calories), var = var(Calories))
```

Question 3

```{r}
boxplot(drinks_content$Calories)
outliers <- boxplot(
  drinks_content$Calories, 
  plot = FALSE)$out

#Found 1 outlier, of 510, where the next value is 460, so I removed the outlier to avoid it pulling up the mean. 
```

Question 4

```{r}
selection <- select(drinks_content, Beverage_category, Beverage, Beverage_prep, Calories)
drop_na(selection)
```

Question 5


```{r}
filter(drinks_content, Beverage_category == "Classic Espresso Drinks")
```

Question 6


```{r}
drink_calories <- drinks_content %>%
  mutate(calorie_diff = Calories - 135)
```

Question 7
```{r}
drinks_grouped <- drinks_content %>%
  group_by(Beverage_prep)


drinks_summary <- drinks_grouped %>%
  summarise(mean_cal = mean(Calories)) %>%
  arrange(desc(mean_cal))
```

Question 8


```{r}
selection <- select(drinks_content, Beverage_category, Beverage, Beverage_prep, Calories)
drop_na(selection)

filter(drinks_content, Beverage_category == "Classic Espresso Drinks")

drink_calories <- drinks_content %>% 
  mutate(calorie_diff = Calories - 135)

drinks_grouped <- drinks_content %>%
  group_by(Beverage_prep)


drinks_summary <- drinks_grouped %>%
  summarise(mean_cal = mean(Calories)) %>%
  arrange(desc(mean_cal))
############

drinks_summary_2 <- drinks_content %>%
  filter(Beverage_category == "Classic Espresso Drinks") %>%
  mutate(calorie_diff = Calories - 135) %>%
  group_by(Beverage_prep) %>%
  summarise(mean_cal = mean(Calories)) %>%
  arrange(desc(mean_cal))
  
```

Question 9

```{r}
max_calories <- drink_calories %>%
  top_n(1, Calories)

min_calories <- drink_calories %>%
  top_n(-1, Calories)
```


Question 10

```{r}
  
above_average_calories <- drinks_grouped %>%
  filter(Calories > mean(Calories))
   
  
```

Question 11

```{r}
drinks_distribution <- drinks_grouped %>%
  filter(Calories(cume_dist(drinks_grouped$Calories) > 0.25) = TRUE)
###ANSWER
drinks_distribution <- drinks_grouped %>%
  filter(cume_dist(desc(Calories)) > 0.25)
```



